fix(vartime_double_base): remove usage of alloc
sp1-patches/curve25519-dalek pull request #9
Opened 2024-11-25 14:43 UTC by rymnc

We replaced the usage of `alloc::Vec`, with a constant-sized slice.

2024-11-25 16:00 UTC, xgreenx approved these changes

2024-11-25 18:29 UTC, jtguibas commented on curve25519-dalek/src/scalar.rs
> +    /// Get the bits of the scalar, in little-endian order, as a slice
cfg flag should be below comment

2024-11-25 19:50 UTC, nhtyy commented on curve25519-dalek/src/scalar.rs
> +    /// Get the bits of the scalar, in little-endian order, as a slice
```suggestion
    /// Get the bits of the scalar, in little-endian order, as a fixed size array
```

2024-11-25 19:50 UTC, nhtyy commented on curve25519-dalek/src/scalar.rs
> +    pub(crate) fn bits_le_slice(&self) -> [bool; 256] {
```suggestion
    pub(crate) fn bits_le_array(&self) -> [bool; 256] {
```

2024-11-25 19:50 UTC, nhtyy commented on curve25519-dalek/src/backend/serial/scalar_mul/vartime_double_base.rs
> +    let a_bits = a.bits_le_slice();
```suggestion
    let a_bits = a.bits_le_array();
```

2024-11-25 19:50 UTC, nhtyy commented on curve25519-dalek/src/backend/serial/scalar_mul/vartime_double_base.rs
> +    let b_bits = b.bits_le_slice();
```suggestion
    let b_bits = b.bits_le_array();
```

2024-11-25 19:52 UTC, nhtyy commented on curve25519-dalek/src/scalar.rs
> +    /// Get the bits of the scalar, in little-endian order, as a slice
```suggestion
    /// Get the bits of the scalar, in little-endian order, as an array
    #[cfg(all(target_os = "zkvm", target_vendor = "succinct"))]
```

2024-11-25 19:53 UTC, nhtyy requested changes
lgtm ty just a nit + johns suggestion

2024-11-26 18:48 UTC, rymnc commented
@nhtyy should be good to go now

2024-11-26 19:22 UTC, merged